apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: spark-streaming
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  # Optional: session token for temporary credentials (required if using temporary AWS credentials)
  AWS_SESSION_TOKEN: ""
  # Optional: for custom S3 endpoints
  AWS_S3_ENDPOINT: ""

